=== wako-app/mobile-sdk/src/manifest-schema.json
{
  "$schema": "http://json-schema.org/schema",
  "id": "WakoManifestSchema",
  "title": "wako manifest Schema for validating manifest JSON.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Link to schema."
    },
    "version": {
      "type": "string",
      "description": "manifest Schema version."
    },
    "id": {
      "type": "string",
      "description": "unique plugin identifier"
    },
    "name": {
      "type": "string",
      "description": "Plugin's name"
    },
    "description": {
      "type": "string",
      "description": "Plugin's description"
    },
    "author": {
      "type": "string",
      "description": "Plugin's author"
    },
    "actions": {
      "type": "array",
      "description": "Where the plugin will be used inside wako",
      "items": {
        "type": "string",
        "enum": [
          "movies",
          "episodes",
          "episodes-item-option",
          "shows",
          "before-movie-middleware",
          "after-movie-middleware",
          "before-show-middleware",
          "after-show-middleware",
          "before-episode-middleware",
          "after-episode-middleware",
          "file-explorer"
        ]
      }
    },
    "entryPointV2": {
      "deprecated": true,
      "type": "string",
      "description": "URL to the plugin's entry point for wako < v6. Could be a absolute URL or a relative one base on the manifest URL. This property is deprecated and will be removed in the future."
    },
    "entryPointV3": {
      "type": "string",
      "description": "URL to the plugin's entry point. Could be a absolute URL or a relative one base on the manifest URL"
    },
    "languages": {
      "type": "object",
      "description": "Plugin languages. "
    },
    "changeLogs": {
      "type": "object",
      "description": "Change logs. The key will be the version and the value the description"
    }
  },
  "required": ["version", "id", "name", "description", "actions", "entryPointV3", "languages"]
}

=== wako-app/mobile-sdk/src/manifest-test.json
{
  "$schema": "manifest-schema.json",
  "version": "1.1.0",
  "id": "plugin.my-plugin",
  "name": "My First Plugin",
  "description": "Will make your life better",
  "author": "",
  "actions": ["movies", "episodes"],
  "entryPointV3": "/plugin.js",
  "languages": {
    "en": "/i18n/en.json",
    "fr": "/i18n/fr.json"
  },
  "changeLogs": {
    "1.1.0": "Improve performance",
    "1.0.0": "Initial Version"
  }
}
